import { readFileSync, writeFileSync } from "fs";
import { load } from "js-yaml";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const yaml = load(readFileSync(resolve(root, "config.yaml"), "utf8"));

const agentIds = Object.fromEntries(
  Object.entries(yaml.agents).map(([name, a]) => [name, a.cursor_agent_id]),
);

const routingRules = yaml.routing.rules.map((r) => {
  // "[plat:question]" → { prefix: "plat", type: "question" }
  const inner = r.trigger_prefix.replace(/^\[|\]$/g, ""); // "plat:question"
  const [prefix, type] = inner.split(":");
  return { prefix, type, route: r.route_to };
});

const allAgents = Object.keys(yaml.agents);
const channelId = yaml.channel_id;
const useThreads = yaml.thread_policy?.use_threads ?? true;

const out = `// AUTO-GENERATED by scripts/gen-config.mjs — do not edit by hand
// Source of truth: config.yaml

export const CHANNEL_ID = ${JSON.stringify(channelId)};

export const ALL_AGENTS = ${JSON.stringify(allAgents)} as const;

export const AGENT_IDS: Record<string, string> = ${JSON.stringify(agentIds, null, 2)};

export interface RoutingRule {
  prefix: string;
  type: string;
  route: string;
}

export const ROUTING_RULES: RoutingRule[] = ${JSON.stringify(routingRules, null, 2)};

export const USE_THREADS = ${useThreads};
`;

writeFileSync(resolve(root, "src", "config.ts"), out);
console.log("✅  src/config.ts generated from config.yaml");
