// AUTO-GENERATED by scripts/gen-config.mjs — do not edit by hand
// Source of truth: config.yaml

export const CHANNEL_ID = "C0B129UQGBD";

export const ALL_AGENTS = ["plat","euler"] as const;

export const AGENT_IDS: Record<string, string> = {
  "plat": "bc-7fde3250-b8ad-4aac-b652-933d5669c9d7",
  "euler": "bc-e058e071-4c90-4917-9af8-40751cf28b63"
};

export interface RoutingRule {
  prefix: string;
  type: string;
  route: string;
}

export const ROUTING_RULES: RoutingRule[] = [
  {
    "prefix": "plat",
    "type": "question",
    "route": "euler"
  },
  {
    "prefix": "plat",
    "type": "finding",
    "route": "euler"
  },
  {
    "prefix": "euler",
    "type": "question",
    "route": "plat"
  },
  {
    "prefix": "euler",
    "type": "finding",
    "route": "plat"
  },
  {
    "prefix": "jigar",
    "type": "question",
    "route": "both"
  },
  {
    "prefix": "jigar",
    "type": "directive",
    "route": "both"
  }
];

export const USE_THREADS = true;
